---
name: actionlint
on:
  push:
    branches: [main]
    paths:
    - .github/**/*.yaml
  pull_request:
    branches: [main]
    paths:
    - .github/**/*.yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    - uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
      with:
        aqua_version: v2.27.3
    - run: actionlint
