---
name: actionlint
on:
  push:
    branches: [main]
    paths:
    - .github/**/*.yaml
  pull_request:
    branches: [main]
    paths:
    - .github/**/*.yaml
jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    - uses: aquaproj/aqua-installer@f13c5d2f0357708d85477aabe50fd3f725528745 # v3.1.0
      with:
        aqua_version: v2.38.1
    - run: actionlint
